name: My first workflow

on: push 

jobs: 
    first_job:
        runs-on: ubuntu-latest
        steps:
           - name: Checkout repo
             uses: actions/checkout@v4

           - name: Pipe
             run: |
              echo "My message"
              ls -ls
              

           #- name: List all files
            # run: ls