name: Example Workflow
on: push 

env:
  GLOBAL_ENV: "applies_to_all_jobs"

jobs: 
  build: 
    runs-on: ubuntu-latest
    env:
      JOB_ENV: "applies_to_this_job"

    steps:
      - name: Print variables
        run: echo "$GLOBAL_ENV $JOB_ENV"