name: Generate ASCII 

on: push 

jobs: 
    ascii: 
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v3

            - name: Executing shell scripts
              run: |
                chmod +x ascii-script.sh
                .github/workflows/ascii-script.sh

            - name: List all files
              run: ls -ltr 


