name: Generate ASCII 

on: push 

jobs:
  run-ascii:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Make script executable
        run: chmod +x scripts/ascii-script.sh

      - name: Run script
        run: ./scripts/ascii-script.sh


